### ISSUE TITLE
Multiple datasets

### ISSUE THREAD

**Issue by thucar** [masalinas/node-red-contrib-chartjs#12]
First of all - awesome work on the node! I've been looking for an alternative to the Dashboard charts for a while now and this looks promising!

Now to my issue - I've not been able to figure out how to have multiple datasets on my chart. I've tried the obvious - just creating two full datasets and combining them to an array:

`[{ "channel": "TP01", "color": "Red", "dataset": [{"x": 1, "y": 10}, {"x": 2, "y": 8 }, {"x": 3, "y": 15}] },{ "channel": "TP02", "color": "Blue", "dataset": [{"x": 1, "y": 20}, {"x": 2, "y": 16 }, {"x": 3, "y": 30}] }]`

but no go.

**Comment by masalinas** [comment]
Hello Thucar,

The multidataset is not implemented in any chartjs node for now. It's a new topic that I would like to include in the next version of the node. This month I recover the sources and update this version and include a multidataset capacity in some charts: linear and vertical or horizontal bars at first. I'll try to manteain a backward compability of the dataset.

Regards

**Comment by thucar** [comment]
May I suggest an easy quickfix? Allow for a json object as an option. So if I wanted to be very specific with the chart setup, I could just pass the whole chart parameter set as a json object, complete with datasets and any other custom options/plugins I would prefer to use.

**Comment by vattenbuffel** [comment]
Any updates on this? :)

**Comment by masalinas** [comment]
The new versión 0.5.1 implement multiserial line charts. Check it out
