### ISSUE TITLE
Timestamp data not rendering as time

### ISSUE THREAD

**Issue by danleighton** [masalinas/node-red-contrib-chartjs#13]
Hi, thanks for doing this node. Really helpful!
I am struggling to work out how to get the unix timestamps to render as dates. Any clues as to how to do it would be very useful!

Here's the data object example going in:

`{
    "channel": "Sentiment",
    "color": "LightGreen",
    "dataset": [{
        "x": 1555691994,
        "y": 4
    }, {
        "x": 1555691994,
        "y": -2
    }]
}`

Many thanks

**Comment by masalinas** [comment]
For manage datetimes in javascript I also use [moment.js](https://momentjs.com/)

**Comment by masalinas** [comment]
to transform dates you could use moment or simple javascript like this:

{x: date.getDate() + "-"+ date.getMonth()+ "-" + date.getFullYear(), y: 5}
