### ISSUE TITLE
changing options for charts

### ISSUE THREAD

**Issue by karlg100** [masalinas/node-red-contrib-chartjs#14]
there does not appear to be a way to change the options for chart.js, for example, disabling animations.  it would be great to add options for chart.js when passing data to the node.
    "options": {
        "animation": {
            "duration": false
        }
example.

**Comment by masalinas** [comment]
Sure could be good implement this new config charts options. I will work on it in the next months. 

Now the new version 0.5.1 implement multi series option only for the linear charts, it could be cool to compare different sires on the same chart.
